x = x.replaceAll(/(class *= *(("[^"]* )|"))align-left([" ])/g, "$1text-left$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))align-right([" ])/g, "$1text-right$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))background-accent([" ])/g, "$1bg-primary$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))background-highlight([" ])/g, "$1bg-warning$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))border-all([" ])/g, "$1brdr-tp brdr-lft brdr-bttm brdr-rght$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))border-bottom([" ])/g, "$1brdr-bttm$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))border-left([" ])/g, "$1brdr-lft$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))border-right([" ])/g, "$1brdr-rght$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))border-top([" ])/g, "$1brdr-tp$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))button button-accent([" ])/g, "$1btn-primary$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))button button-alert([" ])/g, "$1btn-danger$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))button button-attention([" ])/g, "$1btn-warning$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))button button-confirm([" ])/g, "$1btn-success$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))button button-dark([" ])/g, "$1btn-info$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))button-disabled([" ])/g, "$1disabled$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))button-group([" ])/g, "$1btn-group$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))button button-info([" ])/g, "$1btn-primary$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))button-large([" ])/g, "$1btn-lg$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))button-none([" ])/g, "$1btn-link$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))button-small([" ])/g, "$1btn-sm$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))button-toolbar([" ])/g, "$1btn-toolbar$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))button-xlarge([" ])/g, "$1btn-lg$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))button([" ])/g, "$1btn btn-default$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))menu-horizontal([" ])/g, "$1list-inline$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))clearLeft([" ])/g, "$1clearfix$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))clear-left([" ])/g, "$1clearfix$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))clearRight([" ])/g, "$1clearfix$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))clear-right([" ])/g, "$1clearfix$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))clearboth([" ])/g, "$1clearfix$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))clear([" ])/g, "$1clearfix$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))color-accent([" ])/g, "$1text-primary$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))color-attention([" ])/g, "$1text-danger$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))color-medium([" ])/g, "$1text-muted$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))display-block([" ])/g, "$1show$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))equalize([" ])/g, "$1wb-eqht$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))float-left([" ])/g, "$1pull-left$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))float-right([" ])/g, "$1pull-right$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))font-small([" ])/g, "$1small$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))font-xlarge([" ])/g, "$1lead$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))footnote-link([" ])/g, "$1fn-lnk$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))footnote-return([" ])/g, "$1fn-rtn$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))form-alert([" ])/g, "$1has-error$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))form-attention([" ])/g, "$1has-warning$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))form-checkbox form-label-inline([" ])/g, "$1checkbox-inline$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))form-confirm([" ])/g, "$1has-success$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))form-alert([" ])/g, "$1has-error$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))form-attention([" ])/g, "$1has-warning$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))form-confirm([" ])/g, "$1has-success$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))form-label-inline([" ])/g, "$1form-inline$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))form-text-inline([" ])/g, "$1form-inline$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))indent-large([" ])/g, "$1mrgn-lft-lg$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))indent-medium([" ])/g, "$1mrgn-lft-md$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))indent-none([" ])/g, "$1mrgn-lft-0$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))indent-small([" ])/g, "$1mrgn-lft-sm$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))indent-xlarge([" ])/g, "$1mrgn-lft-xl$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))list-bullet-none([" ])/g, "$1list-unstyled$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))list-lower-alpha([" ])/g, "$1lst-lwr-alph$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))list-lower-roman([" ])/g, "$1lst-lwr-rmn$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))list-numeric([" ])/g, "$1lst-num$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))list-upper-alpha([" ])/g, "$1lst-upr-alph$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))list-upper-roman([" ])/g, "$1lst-upr-rmn$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-bottom-large([" ])/g, "$1mrgn-bttm-lg$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-bottom-medium([" ])/g, "$1mrgn-bttm-md$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-bottom-none([" ])/g, "$1mrgn-bttm-0$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-bottom-small([" ])/g, "$1mrgn-bttm-sm$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-bottom-xlarge([" ])/g, "$1mrgn-bttm-xl$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-left-large([" ])/g, "$1mrgn-lft-lg$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-left-medium([" ])/g, "$1mrgn-lft-md$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-left-none([" ])/g, "$1mrgn-lft-0$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-left-small([" ])/g, "$1mrgn-lft-sm$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-left-xlarge([" ])/g, "$1mrgn-lft-xl$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-right-large([" ])/g, "$1mrgn-rght-lg$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-right-medium([" ])/g, "$1mrgn-rght-md$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-right-none([" ])/g, "$1mrgn-rght-0$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-right-small([" ])/g, "$1mrgn-rght-sm$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-right-xlarge([" ])/g, "$1mrgn-rght-xl$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-top-large([" ])/g, "$1mrgn-tp-lg$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-top-medium([" ])/g, "$1mrgn-tp-md$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-top-none([" ])/g, "$1mrgn-tp-0$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-top-small([" ])/g, "$1mrgn-tp-sm$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))margin-top-xlarge([" ])/g, "$1mrgn-tp-xl$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))opacity-10([" ])/g, "$1opct-10$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))opacity-100([" ])/g, "$1opct-100$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))opacity-20([" ])/g, "$1opct-20$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))opacity-30([" ])/g, "$1opct-30$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))opacity-40([" ])/g, "$1opct-40$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))opacity-50([" ])/g, "$1opct-50$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))opacity-60([" ])/g, "$1opct-60$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))opacity-70([" ])/g, "$1opct-70$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))opacity-80([" ])/g, "$1opct-80$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))opacity-90([" ])/g, "$1opct-90$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))print-none([" ])/g, "$1hidden-print$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))uppercase([" ])/g, "$1text-uppercase$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))wet-boew-footnotes([" ])/g, "$1wb-fnote$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))wb-invisible([" ])/g, "$1wb-inv$4");
x = x.replaceAll(/(class *= *(("[^"]* )|"))wrap-none([" ])/g, "$1nowrap$4");
